AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Relationships Service Stack

Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  Neo4jMap:
    Neo4jUri:
      stage: "bolt://34.254.205.98:7687"
      test: "bolt://34.245.93.115:7687"
      prod: "neo4j uri put HERE"
    Neo4jUser:
      stage: neo4j
      test: neo4j
      prod: neo4j
    Neo4jPass:
      stage: i-0033e09261e4a06b5
      test: i-0adfecbd7b86e8ef7
      prod: "instance id should be here"


Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 1024
        Runtime: java8
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            INTERNAL_STREAM_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
            NEO4J_URI: !FindInMap [Neo4jMap, Neo4jUri, !Ref Env]
            NEO4J_USER: !FindInMap [Neo4jMap, Neo4jUser, !Ref Env]
            NEO4J_PASSWORD: !FindInMap [Neo4jMap, Neo4jPass, !Ref Env]
        Tags:
          Company: Ringoid
          Service: relationships
          Environment: !Ref Env

Resources:

  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !Join [ "-", [ !Ref Env, kinesis-consumer-relationships] ]
      Handler: "com.ringoid.events.KinesisConsumer::handler"
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 10

