AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Relationships Service Stack

Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  Neo4jMap:
    Neo4jUris:
      stage: "52.48.255.177"
      test: "34.244.4.133"
      prod: "34.248.225.142"
    Neo4jUser:
      stage: neo4j
      test: neo4j
      prod: neo4j

  FunctionName:
    KinesisConsumerFunction:
      test: test-kinesis-consumer-relationships
      stage: stage-kinesis-consumer-relationships
      prod: prod-kinesis-consumer-relationships
    NewFacesFunction:
      test: test-new-faces-relationships
      stage: stage-new-faces-relationships
      prod: prod-new-faces-relationships
    LikesYouFunction:
      test: test-likes-you-relationships
      stage: stage-likes-you-relationships
      prod: prod-likes-you-relationships
    MatchesFunction:
      test: test-matches-relationships
      stage: stage-matches-relationships
      prod: prod-matches-relationships
    MessagesFunction:
      test: test-messages-relationships
      stage: stage-messages-relationships
      prod: prod-messages-relationships
    ModerationFunction:
      test: test-moderation-relationships
      stage: stage-moderation-relationships
      prod: prod-moderation-relationships
    RedyForPushFunction:
      test: test-readyforpush-relationships
      stage: stage-readyforpush-relationships
      prod: prod-readyforpush-relationships
    LMHISFunction:
      test: test-lmhis-relationships
      stage: stage-lmhis-relationships
      prod: prod-lmhis-relationships
    ChatFunction:
      test: test-chat-relationships
      stage: stage-chat-relationships
      prod: prod-chat-relationships
    FetchForConversionFunction:
      test: test-internal-getConvertObjectsFunction-relationships
      stage: stage-internal-getConvertObjectsFunction-relationships
      prod: prod-internal-getConvertObjectsFunction-relationships
    PrepareNewFacesFunction:
      test: test-internal-prepare-new-faces-relationships
      stage: stage-internal-prepare-new-faces-relationships
      prod: prod-internal-prepare-new-faces-relationships
    DiscoverFunction:
      test: test-discover-relationships
      stage: stage-discover-relationships
      prod: prod-discover-relationships
    GetLcLikesFunction:
      test: test-get-lc-likes-relationships
      stage: stage-get-lc-likes-relationships
      prod: prod-get-lc-likes-relationships
    GetLcMessagesFunction:
      test: test-get-lc-messages-relationships
      stage: stage-get-lc-messages-relationships
      prod: prod-get-lc-messages-relationships

  BotSqsResourcesName:
    BotSqsQueue:
      test: test-bots-sqs-queue
      stage: stage-bots-sqs-queue
      prod: prod-bots-sqs-queue

  BotEnabledMap:
    BotEnableValue:
      test: true
      stage: true
      prod: false

  TableName:
    AlreadyStartedPrepareNFProcessTable:
      test: test-Relationships-AlreadyStartedPrepareNFProccess
      stage: stage-Relationships-AlreadyStartedPrepareNFProccess
      prod: prod-Relationships-AlreadyStartedPrepareNFProccess

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 900
        MemorySize: 1024
        Runtime: java8
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            INTERNAL_STREAM_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
            COMMON_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExportName] ]
            NEO4J_URIS: !FindInMap [Neo4jMap, Neo4jUris, !Ref Env]
            NEO4J_USER: !FindInMap [Neo4jMap, Neo4jUser, !Ref Env]
            BOTS_ENABLED: !FindInMap [BotEnabledMap, BotEnableValue, !Ref Env]
            BOT_SQS_QUEUE_URL: !Ref BotSqsQueue
            ALREADY_STARTED_PREPARE_NF_TABLE: !FindInMap [TableName, AlreadyStartedPrepareNFProcessTable, !Ref Env]
        Tags:
          Company: Ringoid
          Service: relationships
          Environment: !Ref Env

Resources:
  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      FunctionName: !FindInMap [FunctionName, KinesisConsumerFunction, !Ref Env]
      Handler: handle_stream
      CodeUri: ./handle_stream.zip
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
        - AmazonSQSFullAccess
        - SecretsManagerReadWrite
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 5000

  NewFacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: new_faces
      CodeUri: ./new_faces.zip
      FunctionName: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
      Description: New Faces Relationsips function
      Policies:
        - SecretsManagerReadWrite

  DiscoverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: discover
      CodeUri: ./discover.zip
      FunctionName: !FindInMap [FunctionName, DiscoverFunction, !Ref Env]
      Description: Discover Relationsips function
      Policies:
        - SecretsManagerReadWrite

  GetLcLikesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get_lc_likes
      CodeUri: ./get_lc_likes.zip
      FunctionName: !FindInMap [FunctionName, GetLcLikesFunction, !Ref Env]
      Description: GetLC likes Relationsips function
      Policies:
        - SecretsManagerReadWrite

  GetLcMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get_lc_messages
      CodeUri: ./get_lc_messages.zip
      FunctionName: !FindInMap [FunctionName, GetLcMessagesFunction, !Ref Env]
      Description: GetLC messages Relationsips function
      Policies:
        - SecretsManagerReadWrite

  PrepareNewFacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: prepare_new_faces
      CodeUri: ./prepare_new_faces.zip
      FunctionName: !FindInMap [FunctionName, PrepareNewFacesFunction, !Ref Env]
      Description: Prepare New Faces Relationsips function
      Policies:
        - SecretsManagerReadWrite
        - AmazonKinesisFullAccess
        - AmazonDynamoDBFullAccess

  LikesYouFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: likes_you
      CodeUri: ./likes_you.zip
      FunctionName: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
      Description: Likes You Relationships function
      Policies:
        - SecretsManagerReadWrite

  MatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: match
      CodeUri: ./match.zip
      FunctionName: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
      Description: Matches Relationships function
      Policies:
        - SecretsManagerReadWrite

  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: messages
      CodeUri: ./messages.zip
      FunctionName: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
      Description: Messages Relationships function
      Policies:
        - SecretsManagerReadWrite

  LMHISFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: lmhis
      CodeUri: ./lmhis.zip
      FunctionName: !FindInMap [FunctionName, LMHISFunction, !Ref Env]
      Description: LMHIS Relationships function
      Policies:
        - SecretsManagerReadWrite

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: chat
      CodeUri: ./chat.zip
      FunctionName: !FindInMap [FunctionName, ChatFunction, !Ref Env]
      Description: Chats Relationships function
      Policies:
        - SecretsManagerReadWrite

  RedyForPushFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: ready_for_push
      CodeUri: ./ready_for_push.zip
      FunctionName: !FindInMap [FunctionName, RedyForPushFunction, !Ref Env]
      Description: Ready for Push Relationsips function
      Policies:
        - SecretsManagerReadWrite
        - AmazonSQSFullAccess

  FetchForConversionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: fetch_for_conversion
      CodeUri: ./fetch_for_conversion.zip
      FunctionName: !FindInMap [FunctionName, FetchForConversionFunction, !Ref Env]
      Description: Fetch for Conversion Relationsips function
      Policies:
        - SecretsManagerReadWrite

  ModerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, ModerationFunction, !Ref Env]
      Handler: "com.ringoid.api.moderation.Moderation::handler"
      Description: Moderation function
      Policies:
        - SecretsManagerReadWrite
        - AmazonKinesisFullAccess

  AlreadyStartedPrepareNFProcessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [TableName, AlreadyStartedPrepareNFProcessTable, !Ref Env]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH

  #----------------- Bots section ------------------------
  BotSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !FindInMap [BotSqsResourcesName, BotSqsQueue, !Ref Env]
      VisibilityTimeout: 900
  #----------------- End Bots section ------------------------

Outputs:
  NewFacesFunctionExport:
    Value: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, NewFacesFunctionExport] ]
  DiscoverFunctionExport:
    Value: !FindInMap [FunctionName, DiscoverFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, DiscoverFunctionExport] ]
  LikesYouFunctionExport:
    Value: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, LikesYouFunctionExport] ]
  MatchesFunctionExport:
    Value: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MatchesFunctionExport] ]
  MessagesFunctionExport:
    Value: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MessagesFunctionExport] ]
  LMHISFunctionExport:
    Value: !FindInMap [FunctionName, LMHISFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, LMHISFunctionExport] ]
  ChatFunctionExport:
    Value: !FindInMap [FunctionName, ChatFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, ChatFunctionExport] ]
  RedyForPushFunctionExport:
    Value: !FindInMap [FunctionName, RedyForPushFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, RedyForPushFunctionExport] ]
  BotSqsQueueArnExport:
    Value: !GetAtt BotSqsQueue.Arn
    Export:
      Name: !Join [ "-", [ !Ref Env, BotSqsQueueArnExport] ]
  PrepareNewFacesFunctionExport:
    Value: !FindInMap [FunctionName, PrepareNewFacesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, PrepareNewFacesFunctionExport] ]
  GetLcMessagesFunctionExport:
    Value: !FindInMap [FunctionName, GetLcMessagesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, GetLcMessagesFunctionExport] ]
  GetLcLikesFunctionExport:
    Value: !FindInMap [FunctionName, GetLcLikesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, GetLcLikesFunctionExport] ]
