AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Relationships Service Stack

Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  Neo4jMap:
    Neo4jUri:
      stage: "bolt://34.254.188.103:7687"
      test: "bolt://54.154.53.16:7687"
      prod: "neo4j uri put HERE"
    Neo4jUser:
      stage: neo4j
      test: neo4j
      prod: neo4j
    Neo4jPass:
      stage: i-0033e09261e4a06b5
      test: i-0adfecbd7b86e8ef7
      prod: "instance id should be here"

  FunctionName:
    KinesisConsumerFunction:
      test: test-kinesis-consumer-relationships
      stage: stage-kinesis-consumer-relationships
      prod: prod-kinesis-consumer-relationships
    NewFacesFunction:
      test: test-new-faces-relationships
      stage: stage-new-faces-relationships
      prod: prod-new-faces-relationships
    LikesYouFunction:
      test: test-likes-you-relationships
      stage: stage-likes-you-relationships
      prod: prod-likes-you-relationships
    MatchesFunction:
      test: test-matches-relationships
      stage: stage-matches-relationships
      prod: prod-matches-relationships
    MessagesFunction:
      test: test-messages-relationships
      stage: stage-messages-relationships
      prod: prod-messages-relationships
    InternalCleanDbRelationshipsFunction:
      test: test-internal-clean-db-relationships
      stage: stage-internal-clean-db-relationships
      prod: prod-internal-clean-db-relationships

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 1024
        Runtime: java8
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            INTERNAL_STREAM_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
            NEO4J_URI: !FindInMap [Neo4jMap, Neo4jUri, !Ref Env]
            NEO4J_USER: !FindInMap [Neo4jMap, Neo4jUser, !Ref Env]
            NEO4J_PASSWORD: !FindInMap [Neo4jMap, Neo4jPass, !Ref Env]
        Tags:
          Company: Ringoid
          Service: relationships
          Environment: !Ref Env

Resources:

  InternalCleanDbRelationshipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, InternalCleanDbRelationshipsFunction, !Ref Env]
      Handler: "com.ringoid.internal.Clean::handler"
      Description: Internal Clean DB for relationships

  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, KinesisConsumerFunction, !Ref Env]
      Handler: "com.ringoid.events.KinesisConsumer::handler"
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 10

  NewFacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
      Handler: "com.ringoid.api.newfaces.NewFaces::handler"
      Description: New Faces Feed function

  LikesYouFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
      Handler: "com.ringoid.api.lmm.LikesYou::handler"
      Description: Likes You Feed function

  MatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
      Handler: "com.ringoid.api.lmm.Matches::handler"
      Description: Matches Feed function

  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/relationships-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
      Handler: "com.ringoid.api.lmm.Messages::handler"
      Description: Messages Feed function


Outputs:
  NewFacesFunctionExport:
    Value: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, NewFacesFunctionExport] ]
  LikesYouFunctionExport:
    Value: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, LikesYouFunctionExport] ]
  MatchesFunctionExport:
    Value: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MatchesFunctionExport] ]
  MessagesFunctionExport:
    Value: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MessagesFunctionExport] ]

  InternalCleanDbRelationshipsFunctionExport:
    Value: !FindInMap [FunctionName, InternalCleanDbRelationshipsFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalCleanDbRelationshipsFunctionExport] ]
