AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Relationships Service Stack

Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  Neo4jMap:
    Neo4jUris:
      stage: "34.254.188.103"
      test: "54.194.22.99"
      testold: "34.243.28.144"
      prod: "34.244.112.46&34.252.154.250&63.34.22.195"
    Neo4jUser:
      stage: neo4j
      test: neo4j
      prod: neo4j

  FunctionName:
    KinesisConsumerFunction:
      test: test-kinesis-consumer-relationships
      stage: stage-kinesis-consumer-relationships
      prod: prod-kinesis-consumer-relationships
    NewFacesFunction:
      test: test-new-faces-relationships
      stage: stage-new-faces-relationships
      prod: prod-new-faces-relationships
    LikesYouFunction:
      test: test-likes-you-relationships
      stage: stage-likes-you-relationships
      prod: prod-likes-you-relationships
    MatchesFunction:
      test: test-matches-relationships
      stage: stage-matches-relationships
      prod: prod-matches-relationships
    MessagesFunction:
      test: test-messages-relationships
      stage: stage-messages-relationships
      prod: prod-messages-relationships
    InternalCleanDbRelationshipsFunction:
      test: test-internal-clean-db-relationships
      stage: stage-internal-clean-db-relationships
      prod: prod-internal-clean-db-relationships
    ModerationFunction:
      test: test-moderation-relationships
      stage: stage-moderation-relationships
      prod: prod-moderation-relationships

  BotSqsResourcesName:
    BotSqsQueue:
      test: test-bots-sqs-queue
      stage: stage-bots-sqs-queue
      prod: prod-bots-sqs-queue

  BotEnabledMap:
    BotEnableValue:
      test: true
      stage: true
      prod: false

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 900
        MemorySize: 1024
        Runtime: java8
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            INTERNAL_STREAM_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
            NEO4J_URIS: !FindInMap [Neo4jMap, Neo4jUris, !Ref Env]
            NEO4J_USER: !FindInMap [Neo4jMap, Neo4jUser, !Ref Env]
            BOTS_ENABLED: !FindInMap [BotEnabledMap, BotEnableValue, !Ref Env]
            BOT_SQS_QUEUE_URL: !Ref BotSqsQueue
        Tags:
          Company: Ringoid
          Service: relationships
          Environment: !Ref Env

Resources:

  InternalCleanDbRelationshipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, InternalCleanDbRelationshipsFunction, !Ref Env]
      Handler: "com.com.ringoid.internal.Clean::handler"
      Description: Internal Clean DB for relationships

  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 3008
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, KinesisConsumerFunction, !Ref Env]
      Handler: "com.com.ringoid.events.KinesisConsumer::handler"
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
        - AmazonSQSFullAccess
        - SecretsManagerReadWrite
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 2000

  NewFacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
      Handler: "com.com.ringoid.api.newfaces.NewFaces::handler"
      Description: New Faces Feed function
      Policies:
        - SecretsManagerReadWrite


  LikesYouFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
      Handler: "com.com.ringoid.api.lmm.LikesYou::handler"
      Description: Likes You Feed function
      Policies:
        - SecretsManagerReadWrite

  MatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
      Handler: "com.com.ringoid.api.lmm.Matches::handler"
      Description: Matches Feed function
      Policies:
        - SecretsManagerReadWrite

  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
      Handler: "com.com.ringoid.api.lmm.Messages::handler"
      Description: Messages Feed function
      Policies:
        - SecretsManagerReadWrite

  ModerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: relations-service/build/distributions/relations-service-1.0-SNAPSHOT.zip
      FunctionName: !FindInMap [FunctionName, ModerationFunction, !Ref Env]
      Handler: "com.com.ringoid.api.moderation.Moderation::handler"
      Description: Moderation function
      Policies:
        - SecretsManagerReadWrite

  #----------------- Bots section ------------------------
  BotSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !FindInMap [BotSqsResourcesName, BotSqsQueue, !Ref Env]
      VisibilityTimeout: 900
  #----------------- End Bots section ------------------------

Outputs:
  NewFacesFunctionExport:
    Value: !FindInMap [FunctionName, NewFacesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, NewFacesFunctionExport] ]
  LikesYouFunctionExport:
    Value: !FindInMap [FunctionName, LikesYouFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, LikesYouFunctionExport] ]
  MatchesFunctionExport:
    Value: !FindInMap [FunctionName, MatchesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MatchesFunctionExport] ]
  MessagesFunctionExport:
    Value: !FindInMap [FunctionName, MessagesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, MessagesFunctionExport] ]
  InternalCleanDbRelationshipsFunctionExport:
    Value: !FindInMap [FunctionName, InternalCleanDbRelationshipsFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalCleanDbRelationshipsFunctionExport] ]
  BotSqsQueueArnExport:
    Value: !GetAtt BotSqsQueue.Arn
    Export:
      Name: !Join [ "-", [ !Ref Env, BotSqsQueueArnExport] ]
