package com.ringoid.events;

public enum EventTypes {
    AUTH_USER_PROFILE_CREATED,
    AUTH_USER_SETTINGS_UPDATED,
    AUTH_USER_ONLINE,

    IMAGE_USER_UPLOAD_PHOTO,
    IMAGE_USER_DELETE_PHOTO,

    ACTION_USER_LIKE_PHOTO,
    ACTION_USER_VIEW_PHOTO
}
